# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'circket.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 30, 811, 109))
        self.groupBox.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 9, 771, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.bat = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bat.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.bat.setObjectName("bat")
        self.horizontalLayout.addWidget(self.bat)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.bow = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bow.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.bow.setObjectName("bow")
        self.horizontalLayout.addWidget(self.bow)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.ar = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ar.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.ar.setObjectName("ar")
        self.horizontalLayout.addWidget(self.ar)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.wk = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.wk.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.wk.setObjectName("wk")
        self.horizontalLayout.addWidget(self.wk)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(
            QtCore.QRect(130, 180, 511, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.pa = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.pa.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pa.setObjectName("pa")
        self.horizontalLayout_2.addWidget(self.pa)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_10.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.pu = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.pu.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pu.setObjectName("pu")
        self.horizontalLayout_2.addWidget(self.pu)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(
            QtCore.QRect(80, 240, 761, 401))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rbat = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rbat.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.rbat.setObjectName("rbat")
        self.horizontalLayout_4.addWidget(self.rbat)
        self.rbow = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rbow.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.rbow.setObjectName("rbow")
        self.horizontalLayout_4.addWidget(self.rbow)
        self.rar = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rar.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.rar.setObjectName("rar")
        self.horizontalLayout_4.addWidget(self.rar)
        self.rwk = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rwk.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.rwk.setObjectName("rwk")
        self.horizontalLayout_4.addWidget(self.rwk)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.select = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.select.setObjectName("select")
        self.verticalLayout.addWidget(self.select)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_13.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_15.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.team = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.team.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.team.setObjectName("team")
        self.horizontalLayout_5.addWidget(self.team)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.display = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.display.setObjectName("display")
        self.verticalLayout_2.addWidget(self.display)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 21))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.actionNew_Team = QtWidgets.QAction(MainWindow)
        self.actionNew_Team.setObjectName("actionNew_Team")
        self.actionOpen_Team = QtWidgets.QAction(MainWindow)
        self.actionOpen_Team.setObjectName("actionOpen_Team")
        self.actionSave_Team = QtWidgets.QAction(MainWindow)
        self.actionSave_Team.setObjectName("actionSave_Team")
        self.actionEvaluate_Team = QtWidgets.QAction(MainWindow)
        self.actionEvaluate_Team.setObjectName("actionEvaluate_Team")
        self.menuManage_Teams.addAction(self.actionNew_Team)
        self.menuManage_Teams.addAction(self.actionOpen_Team)
        self.menuManage_Teams.addAction(self.actionSave_Team)
        self.menuManage_Teams.addAction(self.actionEvaluate_Team)
        self.menubar.addAction(self.menuManage_Teams.menuAction())
        self.rbat.toggled.connect(self.radiobutton)
        self.rbow.toggled.connect(self.radiobutton)
        self.rar.toggled.connect(self.radiobutton)
        self.rwk.toggled.connect(self.radiobutton)
        self.select.itemDoubleClicked.connect(self.removelist1)
        self.display.itemDoubleClicked.connect(self.removelist2)
        self.bt = 0
        self.bw = 0
        self.a = 0
        self.w = 0
        self.avl = 1000
        self.used = 0

        self.menuManage_Teams.triggered[QtWidgets.QAction].connect(self.menu)
        
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Circket Players"))
        self.groupBox.setTitle(_translate("MainWindow", "Your Selection"))
        self.label.setText(_translate("MainWindow", "Batsman(BAT)"))
        self.bat.setText(_translate("MainWindow", "##"))
        self.label_2.setText(_translate("MainWindow", "Bowler (BOW)"))
        self.bow.setText(_translate("MainWindow", "##"))
        self.label_3.setText(_translate("MainWindow", "Allrounder (AR)"))
        self.ar.setText(_translate("MainWindow", "##"))
        self.label_4.setText(_translate("MainWindow", "Wicket-Keeper (WK)"))
        self.wk.setText(_translate("MainWindow", "##"))
        self.label_12.setText(_translate("MainWindow", "Point Avaiable"))
        self.pa.setText(_translate("MainWindow", "##"))
        self.label_10.setText(_translate("MainWindow", "Point Used"))
        self.pu.setText(_translate("MainWindow", "##"))
        self.rbat.setText(_translate("MainWindow", "BAT"))
        self.rbow.setText(_translate("MainWindow", "BOW"))
        self.rar.setText(_translate("MainWindow", "AR"))
        self.rwk.setText(_translate("MainWindow", "WK"))
        self.label_13.setText(_translate("MainWindow", ">"))
        self.label_15.setText(_translate("MainWindow", "Team Name"))
        self.team.setText(_translate("MainWindow", "####"))
        self.menuManage_Teams.setTitle(
            _translate("MainWindow", "Manage Teams"))
        self.actionNew_Team.setText(_translate("MainWindow", "New Team"))
        self.actionOpen_Team.setText(_translate("MainWindow", "Open Team"))
        self.actionSave_Team.setText(_translate("MainWindow", "Save Team"))
        self.actionEvaluate_Team.setText(
            _translate("MainWindow", "Evaluate Team"))

    def menu(self,action):
        txt=(action.text())
        
        
        if txt=='New Team':
            
            text, ok=QtWidgets.QInputDialog.getText(MainWindow, "Team", "Enter name of team:")
            if ok:
                self.team.setText(str(text))
                self.bt = 0
                self.bw = 0
                self.a = 0
                self.w = 0
                self.avl = 1000
                self.used = 0
                self.select.clear()
                self.display.clear()
            self.show()
            
        if txt=='Save Team':
            count=self.display.count()
            selected=""
            for i in range(count):
                selected+=self.display.item(i).text()
                if i<count:
                    selected+=","
            self.saveteam(self.team.text(), selected, self.used)
        if txt=='Open Team':
            
            self.select.clear()
            self.display.clear()
            self.show()
            self.openteam()
        if txt=='Evaluate Team':
            from evaluate import Ui_Form
            Dialog = QtWidgets.QDialog()
            ui = Ui_Form()
            ui.setupUi(Dialog)
            #print("effieh")
            ret=Dialog.exec()

    def openteam(self):
        cir = sqlite3.connect('mycircket.db')
        circket = cir.cursor()
        s = "select name from teams"
        cur=circket.execute(s)
        teams=[]
        for row in cur:
            teams.append(row[0])
        
        t, ok=QtWidgets.QInputDialog.getItem(MainWindow,"Dream","Choose A Team",teams,0,False)
        if ok and t:
            self.team.setText(t)
        p = "select players, value from teams where name='"+t+"';"
        cur=circket.execute(p)
        row=cur.fetchone()
        selected=row[0].split(',')
        
        self.display.addItems(selected)
        
        
        self.used=int(row[1])
        
        self.avl=1000-int(row[1])
        count=self.display.count()
        for i in range(count-1):
            ply=self.display.item(i).text()
            #print(ply)
            sql="select ctg from stats where player='"+ply+"';"
            
            cur=circket.execute(sql)
            
            row=cur.fetchone()
            #print(row)
            ctgr=row[0]
            #print("ej")
            if ctgr=="BAT":self.bt+=1
            if ctgr=="BWL":self.bw+=1
            if ctgr=="AR":self.a+=1
            if ctgr=="WK":self.w+=1
            self.show()
        

    def saveteam(self, nm, ply, val):
        if self.bt+self.bw+self.a+self.w!=11:
            self.showdlg("Insufficient Players")
            return
        cir = sqlite3.connect('mycircket.db')
        
        s = "insert into teams (name, players, value) values ('"+nm+"','"+ply+"','"+str(val)+"');"
        try:
            circket = cir.cursor()
            circket.execute(s)
            print(s)
            self.showdlg("Team Saved Succesfully")
            cir.commit()
        except:
            self.showdlg("Error in Operation")
            cir.rollback()   
        
                    
            
            
    def show(self):
        


        self.bat.setText(str(self.bt))
        self.bow.setText(str(self.bw))
        self.ar.setText(str(self.a))
        self.wk.setText(str(self.w))
        
        self.pa.setText(str(self.avl))
        self.pu.setText(str(self.used))
           
        


    def radiobutton(self):
             

        ctgr=''
        if self.rbat.isChecked()==True:
            ctgr='BAT'
        if self.rbow.isChecked()==True:
            ctgr='BWL'
        if self.rar.isChecked()==True:
            ctgr='AR'
        if self.rwk.isChecked()==True:
            ctgr='WK'
       	
        self.filllist(ctgr)

    def filllist(self, ctgr):
        if self.team.text() == '####':
                self.showdlg("Enter name of team")
                return
        self.select.clear()
        cir = sqlite3.connect('mycircket.db')
        circket = cir.cursor()
        bat = "select player from stats where ctg='"+ctgr+"';"
        circket.execute(bat)
        result = circket.fetchall()
        for row in result:
            selected=[]
            for i in range(self.display.count()):
                selected.append(self.display.item(i).text())
            if row[0] not in selected:
                
                self.select.addItem(row[0])    

    def removelist1(self, item):
        
        
        cir = sqlite3.connect('mycircket.db')
        circket = cir.cursor()
        p = "select ctg from stats where player='"+item.text()+"';"
        circket.execute(p)
        result = circket.fetchall()
        for i in result:
            for ctgr in i:
                print("")
        ret=self.criteria(ctgr, item)
        if ret==True:
            self.select.takeItem(self.select.row(item))
            
            self.display.addItem(item.text())
            self.show()
    def criteria(self, ctgr, item):
        msg = ''
        if ctgr=="BAT" and self.bt>=5:msg="You can't select more than 5 Batsmen"
        if ctgr=="BWL" and self.bw>=5:msg="You can't select more than 5 Bowler"
        if ctgr=="AR" and self.a>=3:msg="You can't select more than 3 Allrounder"
        if ctgr=="WK" and self.w>=1:msg="You can't select more than 1 wicket keeper"
        if msg!='':
            self.showdlg(msg)
            return False
        if self.avl<=0:
            msg="You have used all your Points"
            self.showdlg(msg)
            return False
        
        
        
        if ctgr=='BAT':self.bt+=1
        if ctgr == 'BWL':self.bw+=1
        if ctgr == 'AR':self.a+=1
        if ctgr == 'WK':self.w+=1
        cir = sqlite3.connect('mycircket.db')
        circket = cir.cursor()
        v = "select value from stats where player='"+item.text()+"';"
        circket.execute(v)
        row = circket.fetchone()
        self.avl-=row[0]
        self.used+=row[0]
        return True
        
    def removelist2(self, item):
        
        
        cir = sqlite3.connect('mycircket.db')
        circket = cir.cursor()
        p = "select ctg from stats where player='"+item.text()+"';"
        circket.execute(p)
        result = circket.fetchall()
        for i in result:
            for ctgr in i:
                print("")
        if ctgr=='BAT':self.bt-=1
        if ctgr == 'BWL':self.bw-=1
        if ctgr == 'AR':self.a-=1
        if ctgr == 'WK':self.w-=1
        self.bat.setText(str(self.bt))
        self.bow.setText(str(self.bw))
        self.ar.setText(str(self.a))
        self.wk.setText(str(self.w))
        self.display.takeItem(self.display.row(item))
        self.select.addItem(item.text())
    
        
        v = "select value from stats where player='"+item.text()+"';"
        circket.execute(v)
        row = circket.fetchone()
        
        
        self.avl+=row[0]
        self.used-=row[0]
        self.pa.setText(str(self.avl))
        self.pu.setText(str(self.used))
        
    def showdlg(self,msg):
        
        Dialog=QtWidgets.QMessageBox()
        Dialog.setText(msg)
        Dialog.setWindowTitle("Dream Team selector")
        ret=Dialog.exec()        

                    


                
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
